export const getUser = (state) => state.user;
export const getTypes = (state) => state.projects.types;
export const getAuthors = (state) => state.projects.authors;
export const getProjects = (state) => state.projects.projects;
export const getSelectedType = (state) => state.projects.selectedType;
export const getSelectedAuthor = (state) => state.projects.selectedAuthor;
export const getSelectedProject = (state) => state.projects.selectedProject;
export const getPage = (state) => state.projects.activePage;
export const getLimit = (state) => state.projects.limit;
export const getTotalCount = (state) => state.projects.totalCount;
export const getBasket=state=>state.basket;
export const getImages=state=>state.images;
